name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install mdslides
        run: python -m pip install git+https://gitlab.com/da_doomer/markdown-slides.git
      - name: Generate slides
        run:  mdslides ./slides/kafka-101.md --output_dir docs
      - name: Checkout to slides branch
        run: |
          git pull
          git checkout slides
      - name: Delete unused files
        run: |
          rm -r .github
          rm -r slides
          rm README.md
          rm .gitignore
      - name: Push all code to slides branch
        run: |
          git config --global user.email "26169430+KingChampion36@users.noreply.github.com"
          git config --global user.name "KingChampion36"
          git add .
          git commit -m "Slides generated"
          git push --force origin slides
  
