name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        run: actions/checkout@v3
      - name: Install mdslides
        run: python -m pip install git+https://gitlab.com/da_doomer/markdown-slides.git
      - name: Generate slides
        run:  mdslides ./slides/kafka-101.md
      - name: Checkout to slides branch
        run: git checkout -b slides
      - name: Push all code to slides branch
        run: git push --force origin slides
  
